CREATE TABLE [dbo].[User]
(
	[ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [AddressID] UNIQUEIDENTIFIER NOT NULL, 
    [Active] BIT NOT NULL, 
    [CreationDate] DATETIME NOT NULL, 
    [DeleteDate] DATETIME NULL, 
    [CompanyID] UNIQUEIDENTIFIER NOT NULL, 
    [InstanceID] UNIQUEIDENTIFIER NOT NULL
)
